env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/prop-types: 0
  react/no-unescaped-entities: 0
  react/display-name: 0
